### ISSUE TITLE
Do not assign labels & annotations in Elastic using controller

### ISSUE THREAD

**Issue by aerokite** [k8sdb/elasticsearch#48]
```yaml
apiVersion: k8sdb.com/v1beta1
kind: Elastic
metadata:
  annotations:
    elastic.k8sdb.com/version: canary
  creationTimestamp: 2017-05-09T05:10:30Z
  labels:
    k8sdb.com/type: elastic
  name: elasticsearch-demo
  namespace: default
```

Fix here: https://github.com/k8sdb/elasticsearch/blob/master/pkg/controller/create.go#L116
